version: '3'

services:
  elasticsearch-spring-boot-container1:
    image: elasticsearch-spring-boot-compose:v0.1b
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/elasticsearch-spring-boot-container1
    ports:
      - "8090:8090"